//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTwoWheels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserComment
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public string UserId { get; set; }
        public Nullable<int> UserPostId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUserPost AspNetUserPost { get; set; }
    }
}
