//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTwoWheels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUserPost()
        {
            this.AspNetUserComments = new HashSet<AspNetUserComment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public byte[] Thumbnail { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserComment> AspNetUserComments { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
